---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - action.yml
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch: {}

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Mojo
        id: setup-mojo
        uses: ./
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "mojo should be installed" \
            "${{ steps.setup-mojo.outputs.installed }}" \
            "true"
      - name: Validate script
        run: |
          unique_key="$(date +%s)"
          project_name="project-${unique_key}"
          script_filename="script-${unique_key}.mojo"

          pixi init "${project_name}" \
            -c https://conda.modular.com/max-nightly/ \
            -c conda-forge
          cd "${project_name}"

          pixi add modular
          pixi run mojo --version

          echo 'def main():' > "${script_filename}"
          echo '    print("Hello, world!")' >> "${script_filename}"
          [ "$(pixi run mojo "${script_filename}")" = "Hello, world!" ] || exit 1;
        working-directory: ${{ runner.temp }}

  test-force:
    name: Test force
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        force: ["true", "false"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup mojo 1
        id: setup-mojo-1
        uses: ./
      - name: Setup mojo 2
        id: setup-mojo-2
        uses: ./
        with:
          force: ${{ matrix.force }}
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "Wrong \"installed\" output from setup-mojo-1" \
            "${{ steps.setup-mojo-1.outputs.installed }}" \
            "true"
          test_equal "Wrong \"installed\" output from setup-mojo-2" \
            "${{ steps.setup-mojo-2.outputs.installed }}" \
            "${{ matrix.force }}"
